### ISSUE TITLE
Add snyk or tfsec or checkov for security scanning

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-metrics-terraform#2]

**Comment by patheard** [comment]
* Scanning with Snyk CLI is now being tested in #61 
* Support ticket has been raised with Snyk regarding automated PR scans (they do not appear to pickup IaC files - only the `package.json` of the lambda was found).

Todo:

- [ ] Ignore some vulnerabilities (e.g. MUTABLE ECR check)
- [ ] Investigate using `--sarif` output to add security scan results to project's "Security" tab.

**Comment by patheard** [comment]
Confirmed with Snyk support that:

* Snyk default PR test does not test `*.tf` files yet.  Workaround is to use the CLI with `snyk iac test` command.
* The `snyk iac test` command does not support ignoring vulnerabilities in a `.snyk` policy file.  The only way to ignore vulnerabilities is through the GUI, and this ignore is only used for the schedules weekly scans (not by ad-hoc `snyk iac test` commands).

**Comment by patheard** [comment]
# Scan output

* [checkov-scan.txt](https://github.com/cds-snc/covid-alert-metrics-terraform/files/6570349/checkov-scan.txt)
* [tfsec-scan.txt](https://github.com/cds-snc/covid-alert-metrics-terraform/files/6570350/tfsec-scan.txt)

# Issues found

```sh
# Checkov
Passed checks: 102, Failed checks: 17, Skipped checks: 0

# tfsec
11 potential problems detected.
```

## Same vulnerabilities identified
```sh
# CloudWatch log groups
Default encryption used - should use KMS

# S3 buckets
Versionning not enabled

# ECR
Ensure that ECR repositories are encrypted 
Ensure ECR Image Tags are immutable

# DynamoDB
Ensure Dynamodb point in time recovery (backup) is enabled

```

## Checkov only
```sh
# S3 buckets
Ensure that S3 bucket has cross-region replication enabled
Ensure S3 bucket has MFA delete enabled

# Lambda
X-ray tracing is enabled for Lambda
Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ)
Ensure that AWS Lambda function is configured for function-level concurrent execution limit

# IAM policy
Ensure IAM policies does not allow write access without constraints
```

## tfsec only
```sh
# Security group rule
Fully open egress security group rule
```

**Comment by patheard** [comment]
Next step is to update `*.tf` files with failures.
