### ISSUE TITLE
Migrate metrics from Terraform Repo to Teragrunt Repo

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-metrics-terraform#50]
Now that we have a nice clean Terragrunt repo for metrics we need to migrate over all the metrics repo from the keyserver.

- [x] aggregate_metrics table
- [x] raw_metrics table
- [x] dead letter queue
- [x] backoff retry lambda
- [x] aggregate_metrics lambda
- [x] raw_metrics lambda
- [x] api_gateway
- [x] cloudwatch alarms
- [x] cloudwatch dashboard

**Comment by patheard** [comment]
Metrics have been migrated 🎉
