### ISSUE TITLE
Bug: fix issue where an alarm keeps changing...

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-metrics-terraform#70]
# aws_cloudwatch_metric_alarm.backoff_retry_average_duration will be updated in-place
  ~ resource "aws_cloudwatch_metric_alarm" "backoff_retry_average_duration" {
      ~ alarm_description         = "This metric monitors average duration for the save_metrics lambda" -> "This metric monitors average duration for the backoff_retry lambda"
      ~ dimensions                = {
          ~ "FunctionName" = "save-metrics" -> "backoff_retry"
        }
        id                        = "save-metrics-average-duration"
        tags                      = {}
        # (16 unchanged attributes hidden)
    }

**Comment by patheard** [comment]
Alarm is no longer changing names with each `tf plan` 🎉
